/* generated by build.mjs — do not edit */
const V = "site-3c8d1455";
const ASSETS = ["index.html","movies.html","essays.html","books.html","./"];
self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(V).then((c) => c.addAll(ASSETS).catch(() => {})));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((k) =>
    Promise.all(k.filter((x) => x !== V).map((x) => caches.delete(x)))
  ).then(() => self.clients.claim()));
});
// Network-first, cache as fallback: fast, offline-capable, and never
// serves you a stale page after a push.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(
    fetch(e.request)
      .then((res) => {
        if (res && res.ok) { const copy = res.clone(); caches.open(V).then((c) => c.put(e.request, copy)); }
        return res;
      })
      .catch(() => caches.match(e.request).then((hit) => hit || Response.error()))
  );
});
