/* generated by build.mjs — do not edit */
const V = "site-54ece5b4";
const ASSETS = ["index.html","movies.html","essays.html","books.html","./"];
self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(V).then((c) => c.addAll(ASSETS).catch(() => {})));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((k) =>
    Promise.all(k.filter((x) => x !== V).map((x) => caches.delete(x)))
  ).then(() => self.clients.claim()));
});
// Network-first, falling back to cache. The network is normally ~30ms,
// so this stays fast while guaranteeing you never see a stale page
// after pushing an update. The cache is what makes it work offline.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(
    fetch(e.request)
      .then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(V).then((c) => c.put(e.request, copy));
        }
        return res;
      })
      .catch(() => caches.match(e.request).then((hit) => hit || Response.error()))
  );
});
